apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rancher-keycloak-operator.fullname" . }}
  labels:
    {{- include "rancher-keycloak-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["waldur.io"]
    resources:
      - managedrancherprojects
      - managedrancherprojects/status
      - rancherprojectinventories
      - rancherprojectinventories/status
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rancher-keycloak-operator.fullname" . }}
  labels:
    {{- include "rancher-keycloak-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rancher-keycloak-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rancher-keycloak-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
