{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher-keycloak-operator.fullname" . }}
  labels:
    {{- include "rancher-keycloak-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  RANCHER_URL: {{ .Values.config.rancher.url | quote }}
  RANCHER_BEARER_TOKEN: {{ .Values.config.rancher.bearerToken | quote }}
  RANCHER_VERIFY_SSL: {{ .Values.config.rancher.verifySsl | quote }}
  CR_NAMESPACE: {{ .Values.config.crNamespace | quote }}
  {{- if .Values.config.keycloak.url }}
  KEYCLOAK_URL: {{ .Values.config.keycloak.url | quote }}
  KEYCLOAK_REALM: {{ .Values.config.keycloak.realm | quote }}
  KEYCLOAK_USERNAME: {{ .Values.config.keycloak.username | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.config.keycloak.password | quote }}
  KEYCLOAK_USER_REALM: {{ .Values.config.keycloak.userRealm | quote }}
  KEYCLOAK_VERIFY_SSL: {{ .Values.config.keycloak.verifySsl | quote }}
  {{- end }}
{{- end }}
